### PR TITLE
CryptManager handles evilness when visit Cyrpt

### PR DESCRIPTION
**Pull request by Veracity0**
These properties:
```
user	cyrptAlcoveEvilness	0
user	cyrptCrannyEvilness	0
user	cyrptNicheEvilness	0
user	cyrptNookEvilness	0
user	cyrptTotalEvilness	0
```
track the state of undefiling the four corners of the Cyrpt.

We detected them when examining the Evilometer.

1) Correct them when visiting the Cyrpt and seeing that corners are empty.
2) If the Haert is visible, total Evilness is 999.
3) If the Cyrpt is empty, total evilness is 0
4) Centralize decrementing evilness to decrement both the specific zone's property and total evilness.
When total evilness hits 0, set it to 999, since the Bonerdagon is waiting for you.
5) When you defeat a subboss, set evilness to 0 in that corner
6) When you defeat the Bonerdagon, set total evilness to 0 and advance quest to step1

CryptManager has exported methods:

acquireEvilometer - sets those properties and starts the quest
examineEvilometer (formerly in UseItemRequest) - corrects properties, as needed
visitCrypt (called from QuestManager) - new. corrects properties, as needed
decorateCrypt (formerly in RequestEditorKit) - shows Evilometer in Relay Browser
evilZoneProperty - given AdventurePool constant, return the property that tracks evilness
setEvilness, decreaseEvilness - for a zone, and also handles total evilness
defeatBoss - for subzones and the Bonerdagon

This is good to go.

### CODE REVIEW

**Comment by Veracity0** [comment]
I haven't run today's WereProfessor turns yet, so I'll finish the Cyrpt quest today - even though I would normally wait until tomorrow.

I centralized evilness decrementing into CryptManager. I want to get HTML first defeating a sub boss and also the Bonerdagon and write tests to verify the evilness properties update correctly.

So,I should finish this PR today.

**Comment by Veracity0** [comment]
I don't even know how to begin debugging the test failure in a completely unrelated test suite.
I assume there is leakage of some sort. Odd, since I copied and modified tests from FightRequestTest.

**Comment by Veracity0** [comment]
I give up.

**Comment by gausie** [comment]
I can take a look for the leak this afternoon if you like. It’s annoying but enough breakpoints and i can usually find them

**Comment by Veracity0** [comment]
> I can take a look for the leak this afternoon if you like. It’s annoying but enough breakpoints and i can usually find them

I'd appreciate that, thanks.

When I had failing tests in DebugModifiersTest, I put debug prints into those tests - and they no longer failed.
The tests no longer fail on my computer. Only on github.

It's really annoying, since I modeled my tests on passing tests in FightRequestTest, which work fine.

**Comment by jaadams5** [comment]
Passed locally for me on Windows 10.  I haven't looked at all of the failures but if they are intermittent and not obviously related to the new code a case could be made to accept them and move on.

**Comment by Veracity0** [comment]
Looking at a failing test in DebugModifiersTest:
```
  @Test
  void listsWaterLevelExp() {
    try (var cleanups =
        new Cleanups(withPath(AscensionPath.Path.HEAVY_RAINS), withLocation("Noob Cave"))) {
      evaluateDebugModifiers(DoubleModifier.EXPERIENCE);
      assertThat(output(), containsDebugRow("Path", "Water Level*10/3", 10.58, 10.58));
    }
  }
```
I added a print if output().indexOf("10.58") == -1 and it actually printed something.

<table border=2><tr><td>type</td><td>source</td><td colspan=2>Experience</td><td colspan=2>Muscle Experience</td><td colspan=2>Mysticality Experience</td><td colspan=2>Moxie Experience</td><td colspan=2>Familiar Experience</td><td colspan=2>Muscle Experience Percent</td><td colspan=2>Mysticality Experience Percent</td><td colspan=2>Moxie Experience Percent</td></tr><tr><td>Path</td><td>Water Level*10/3</td><td>+16.67</td><td>=&nbsp;+16.67</td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td></tr><tr><td>Class</td><td>EXP/2</td><td></td><td></td><td>+16.83</td><td>=&nbsp;+16.83</td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td></tr><tr><td>Class</td><td>EXP/4</td><td></td><td></td><td></td><td></td><td>+7.92</td><td>=&nbsp;+7.92</td><td>+7.92</td><td>=&nbsp;+7.92</td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td></tr></table><br>

Isn't that interesting.

The Noob Cave is underground - water level 5 - and (5 * 10) / 3 == 16.67
Which is to say, this is the expected result.

But the test expects to get 10.58. (10.58 * 3) / 10 == 3.174

That makes no sense at all.

And what's with the class experience stuff?

**Comment by jaadams5** [comment]
I merged main in to https://github.com/kolmafia/kolmafia/pull/1889 and saw a failure with CustomScriptTest that I also saw with CryptManager.  So the failure can intermittently occur without CryptManager.

**Comment by Veracity0** [comment]
I submitted a fix for the water level test. Here are the remaining failures:
```
  void listsStatExpNormal() {
    try (var cleanups =
        new Cleanups(withClass(AscensionClass.SEAL_CLUBBER), withEquipped(ItemPool.SUGAR_SHIRT))) {
      evaluateDebugModifiers(DoubleModifier.MUS_EXPERIENCE);
      if (output().indexOf("3.0") == -1) System.out.println(output());
      assertThat(output(), containsDebugRow("Class", "EXP/2", 3.0, 3.0));
```
prints
<table border=2><tr><td>type</td><td>source</td><td colspan=2>Muscle Experience</td><td colspan=2>Muscle Experience Percent</td></tr><tr><td>Class</td><td>EXP/2</td><td>+15.00</td><td>=&nbsp;+15.00</td><td></td><td></td></tr></table><br>

```
  void listsStatExpTuned() {
    try (var cleanups =
        new Cleanups(
            withClass(AscensionClass.SEAL_CLUBBER),
            withAllEquipped(ItemPool.SUGAR_SHIRT, ItemPool.MIME_ARMY_INSIGNIA_INFANTRY))) {
      evaluateDebugModifiers(DoubleModifier.MUS_EXPERIENCE);
      if (output().indexOf("5.0") == -1) System.out.println(output());
      assertThat(output(), containsDebugRow("Class", "EXP", 5.0, 5.0));
```
prints

<table border=2><tr><td>type</td><td>source</td><td colspan=2>Muscle Experience</td><td colspan=2>Muscle Experience Percent</td></tr><tr><td>Class</td><td>EXP</td><td>+29.00</td><td>=&nbsp;+29.00</td><td></td><td></td></tr></table><br>

**Comment by Veracity0** [comment]
The issue is that the Experience modifiers depend on the Location you are adventuring in; KoLmafia uses the average monster level to estimate what XP you get.

1) The DebugModifiersTest should use withLocation("Noob Cave") to get the expected results, regardless of leaks.
2) CryptManagerTest should use withLocation, rather than withLastLocation.

**Review by midgleyc — APPROVED** [review]

**Pull request merged**
