### PR TITLE
Fix outfit swapping with empty accessory slots.

### PR DESCRIPTION
**Pull request by heeheehee-kolmafia**
The trigger seems to be having an accessory in acc1 and an empty slot
in some higher value, then donning an outfit that fills that empty
slot.

Note: not ready for commit as-is, as I haven't written any tests
yet. I've only confirmed that the fix works :)

### CODE REVIEW

**Comment by midgleyc** [comment]
I think this is also the cause of the issues people have been having with maximizer and accessories: some combination of outfit changes leads `EquipmentManager.ACCESSORY_SLOTS` to not contain all the accessories (i.e. it contains duplicates). I can't replicate this, though.

**Comment by midgleyc** [comment]
Ah, I see you knew about this already.

**Comment by gausie** [comment]
OHHHHHHH reading your change this was a dumb thing for me to have done. Sorry everyone. Thanks for the fix.

**Comment by gausie** [comment]
I want to just merge this since it's an important hot fix that will be hard to test. If tests are forthcoming later that would be fantastic

**Review by gausie — APPROVED** [review]

**Pull request merged**
