### PR TITLE
my_total_turns_spent() to return the sum of all $location[] turns_spent

### PR DESCRIPTION
**Pull request by Rinn**
Keeping track of the turns in a separate Integer in AdventureSpentDatabase to prevent the need to reducing the Map values every time the function is called

### CODE REVIEW

**Comment by horrible-little-slime** [comment]
This would be extremely useful to me! I do enough free fights that I can't really use `total_turns_spent` to determine if I've done something meaningful during my last turn (as opposed to, say, hitting a june cleaver NC or zone intro NC or whatever)

That being said, I think `my_delay_turncount` might be a little more natural a name. I'm mostly thinking about when it gets camelcased in js: `myDelayturncount` vs `myDelayTurncount`

**Comment by Rinn** [comment]
ya i'll rename it when i get home

**Review by jaadams5 — APPROVED** [review]

**Comment by midgleyc** [comment]
Naming-wise: how is `delay` related to this? It looks like it's more the total combats. If they were in a delayed zone, you'd be reducing delay, but they aren't necessarily.

**Comment by gausie** [comment]
Agree with Ryo - the naming sounds odd.

**Comment by Rinn** [comment]
I'm not attached to the function name i just didn't want it anyone to confuse it with my_turncount()

**Comment by Rinn** [comment]
changed it to my_total_turns_spent

**Review by midgleyc — APPROVED** [review]
righto -- as the sum of `turns_spent` on all locations this is reasonably self-descriptive

**Pull request merged**
