### PR TITLE
On purchase, include player id, and total cost in the CLI message

### PR DESCRIPTION
**Pull request by libraryaddict**
Player run store

> Purchasing BACON (5 @ 100 = 500) from #3272033...

NPC store

> Purchasing chewing gum on a string (2 @ 47 = 94)...

### CODE REVIEW

**Comment by gausie** [comment]
I'm neutral on this change, learning towards reject. I'll let someone else weigh in.

**Comment by jaadams5** [comment]
The change does break some session log parsing.

I wouldn't have spent the time to do it but I can lean towards approval.

**Comment by libraryaddict** [comment]
> The change does break some session log parsing.

To be clear, you mean session log parsing by third parties?
This shouldn't effect the sessions file I believe, and the CLI has a max line limit regardless.

**Comment by jaadams5** [comment]
> > The change does break some session log parsing.
> 
> To be clear, you mean session log parsing by third parties? This shouldn't effect the sessions file I believe, and the CLI has a max line limit regardless.

Definitely third party parsers.

**Review by jaadams5 — APPROVED** [review]

**Pull request merged**
