### PR TITLE
Add missing zap groups

### PR DESCRIPTION
**Pull request by libraryaddict**
Wiki suggests "devil hair pasta, Hell ramen, spagecialetti" yet this is already somewhat defined. Not sure who is accurate.

This list is compiled from individual wiki pages, the zapping page on wiki still needs updating.

### CODE REVIEW

**Comment by midgleyc** [comment]
For context, the existing line 20 is:
```
fettucini Inconnu, gnocchetti di Nietzsche, Hell ramen, spaghetti with Skullheads
```

You've added an extra group for fettucini Inconnu but not the others, and left this as-is.

I think the above line should be deleted entirely, and replaced with
```
devil hair pasta, Hell ramen, spagecialetti
fettucini Inconnu, linguini immondizia bianco, shells a la shellfish
gnocchetti di Nietzsche, spaghetti with Skullheads
```

I think this happened during the Pasta revamp in 2015.

Nice work tracking everything down!

**Comment by libraryaddict** [comment]
Changes has been made as requested.

**Comment by midgleyc** [comment]
line 199 is also fettucini Inconnu ;)

**Comment by libraryaddict** [comment]
Huh, Ctrl+F failed me. Fixed.

**Comment by midgleyc** [comment]
sweet, LGTM

**Review by gausie — APPROVED** [review]
Fantastic! Thank you for your work

**Pull request merged**
