### PR TITLE
Track hallowiener encounters

### PR DESCRIPTION
**Pull request by libraryaddict**
Tracks the encounters as marked in https://kol.coldfront.net/thekolwiki/index.php/Hallowiener_Dog

As I do not own a haunted doghouse, I am unable to generate the html needed for tests, and am unable to test this myself.

As dark friar woods all share the same NC, the intention is to rely on the "Adventure Again" link's snarfblat.
I'm not certain if the snarfblat will always be in the encounter text.

Thanks @Veracity0 and ReverKiller for helping provide the html needed!

- [x] Has html for 8 bit realm
- [x] Has html for beach buck
- [x] Has html for coinspiracy
- [x] Has html for sonofa beach
- [x] Has html for volcano
- [x] Has html for Middle Chamber
- [x] Has html for gauno junction
- [x] Has html for Madness Bakery
- [x] Has html for Overgrown Lot
- [x] Has html for Skeleton store
- [x] Has html for Smut Orcs
- [x] Has html for Defiled Nook
- [x] Has html for knoll gym

Beach Bucks and Funfunds are not tracked as they are recurring.

# The following are not tracked as KoL seemingly accidentally removed them.
- [ ] Has html for Dark Elbow
- [ ] Has html for Dark Heart
- [ ] Has html for Dark Neck

### CODE REVIEW

**Comment by gausie** [comment]
Great! Just needs those tests whenever you can arrange them

**Comment by libraryaddict** [comment]
> Great! Just needs those tests whenever you can arrange them

Which is very unlikely to occur anytime soon, remembering I don't own the iotm.
For now, this PR will sit.

Might open a thread in the forums in a week or two.

**Comment by midgleyc** [comment]
Doggy Heaven replaces the 50 adventure, so you can get it an unlimited number of times (every 50 turns spent).

So it should either be a number (to track how many FunFunds you got) or untracked (because you can get it an unlimited number of times).

**Review by midgleyc — APPROVED** [review]
Thanks!

**Pull request merged**
