### PR TITLE
Add Crimbo 21 Items and Effects

### PR DESCRIPTION
**Pull request by matt-chugg**
First pull request, apologies if it isn't right

### CODE REVIEW

**Comment by gausie** [comment]
@matt-chugg thanks for the PR! i would expect to see some changes to other files here:

* modifiers.txt will tell us what the items and effects do
* i'd expect to see the new booze in inebriety.txt
* and the new food in fullness.txt

We also need to add the new shop, but that doesn't need to come in this PR

**Comment by matt-chugg** [comment]
Fair enough, understood, 
Was posting here as a PR when I would normally post on kolmafia.us, someone suggested data updates would be better in pull requests, and that's normally the extent of the data which comes from debug logs, I'll have a dig back through historic commits  for examples and submit a new PR (if I get time before someone else does it!)

**Comment by matt-chugg** [comment]
> and that's normally the extent of the data which comes from debug logs

Apologies, that isn't a fair statement, there is of course all the data I need!

**Comment by jaadams5** [comment]
I added some Advent calendar items in https://github.com/kolmafia/kolmafia/pull/316

It was a PITA for me because whatever I did to get from the forum post to the text files trashed the tabs even though quoting the session log was supposed to preserve them.  I think the culprit was my IDE but I have not confirmed and fixed.

**Comment by jaadams5** [comment]
I also note failing tests.  My recollection is that I wrote the data file consistency tests to catch at least some of the tabs vs. spaces issues.  So that failure suggests there might be some editing to do.

**Comment by matt-chugg** [comment]
- Have added fullness and inebriety
- Have added effect in modifiers

How do I add the source of Sauna-Fresh ? Its choice 145 option 1

**Review by gausie — APPROVED** [review]
Looks good to me!

**Comment by gausie** [comment]
> How do I add the source of Sauna-Fresh ? Its choice 145 option 1

I'm not sure its possible or necessary (and I assume that's a typo for 1457 or something)

**Pull request merged**
