### PR TITLE
feat: make led candle a modeable

### PR DESCRIPTION
**Pull request by midgleyc**
Make maximizer aware of LED candle modes.

Fix the issue introduced in #2025 where moded Jill was being treated as a half-weight (whatever) instead of 1.5x weight. I don't know why the previous code was only setting weight if 0, or why it was using weight and not capped weight -- does anyone else have any idea?

### CODE REVIEW

**Comment by midgleyc** [comment]
okay, as from the failing test, it's because familiars like Wizard Action Figure are fractional fairies.

**Comment by midgleyc** [comment]
Need to go back to the design phase here.

**Comment by midgleyc** [comment]
I think metallic foil radar dish implies the intent was for it to work the way I thought it worked, but it doesn't work that way.

**Comment by midgleyc** [comment]
I was initially going to fix the issues with `switch` not including the led candle in this PR, but I think it's still valuable to go in without.

**Comment by midgleyc** [comment]
@kolmafia/staff -- any comments?

**Review by jaadams5 — APPROVED** [review]

**Comment by jaadams5** [comment]
> @kolmafia/staff -- any comments?

I wasn't sure it was ready and I wasn't sure I had much to contribute.  But to the extent of my ability, it looks OK.

**Comment by midgleyc** [comment]
Yeah, it's ready. There's still stuff to do, but I wanted to draw a line under where we are so far.

**Pull request merged**
