### PR TITLE
feat: consider free rests from mayam chair

### PR DESCRIPTION
**Pull request by midgleyc**

### CODE REVIEW

**Review by gausie — COMMENTED** [review]
Hmmm. If you reset your calendar I assume you keep the old rests. We need to support resetting anyway, but we should probably track the rests separately.

**Comment by midgleyc** [comment]
ah yes, and presumably you can do the chair twice for +10 rests?

**Comment by gausie** [comment]
I haven't tested, but I assume/hope so! If you can't I'll take it up as a bug with CDM.

**Review by gausie — APPROVED** [review]
Hadn't spotted the changes since my last review, apols.

**Pull request merged**
