### PR TITLE
feat: remove validate gradle wrapper action

### PR DESCRIPTION
**Pull request by midgleyc**
This action is failing far too often (as a false positive: failing to access some website) to be worth doing.

The aim is to avoid being vulnerable to a social engineering attack where an outsider upgrades gradle; to avoid that we can just always ensure that we only update gradle ourselves.

### CODE REVIEW

**Review by Veracity0 — APPROVED** [review]
We don't have any sort of "auto upgrade" for gradle.
So, when (and why) do we decide to upgrade gradle?

**Comment by jaadams5** [comment]
I haven't noticed the failures.

I do not do anything to maintain Gradle on my Windows system.  I do "gradlew <some task>" and sometimes that operation decides there is a newer version of gradle and AFAIK fetches it and "installs" it.  So as a user I see gradle as automatically updating with no user action.  I would like that to continue without any change in my behavior.  I can't tell if this still supports that or not.

**Comment by midgleyc** [comment]
This only affects a GitHub workflow and shouldn't affect local behaviour at all.

Previously I've updated gradle when I've seen there's been a new version. I don't think we have any schedule for checking, and I've not been able to find a local tool, though I expect Renovate could handle it if we wanted to.

**Comment by jaadams5** [comment]
OK my updates were caused by "your" action and this doesn't change that.  Thank you.

**Pull request merged**
