### PR TITLE
Remove HTML from CompactSidePane.

### PR DESCRIPTION
**Pull request by phulin**
Much like the equipment PR, rendering HTML in the side pane is unnecessary computational effort. This PR removes HTML from the side pane rendering code in favor of native Java layout tools. It's not a huge speedup but seems to be a reduction of 1-2% of CPU time in my tests.

### CODE REVIEW

**Review by midgleyc — CHANGES_REQUESTED** [review]
There looks to be a small unintended change: previously, the tooltip (hover text) on the familiar read "<Familiar type> (X lbs)". Now it reads "<Player name>'s <Familiar type> (X lbs)". Can we go back to the previous text?

**Comment by phulin** [comment]
Sorry, where do you see that? Here's what mine shows, this must be somewhere else:

image

**Comment by midgleyc** [comment]
No, it's exactly there. Mine has the player name before the familiar type. How odd.

**Review by midgleyc — APPROVED** [review]
issue unrelated to PR but still weird

**Comment by Veracity0** [comment]
My hover text is fine.
However.

Screen Shot 2022-12-31 at 12 33 54 PM

**Comment by phulin** [comment]
Ah, a possibility I didn't consider. WIll fix.

**Pull request merged**
