### PR TITLE
Update location only if changed.

### PR DESCRIPTION
**Pull request by phulin**
Another performance hotspot. I don't believe there is any reason to recalculateAdjustments, setLocation, updateStatus, or fire the preference change if location hasn't changed.

### CODE REVIEW

**Comment by gausie** [comment]
Check out the coverage report, should be very easy to hit 100% on your two new classes

**Review by jaadams5 — DISMISSED** [review]

**Comment by phulin** [comment]
> Check out the coverage report, should be very easy to hit 100% on your two new classes

Which ones? This PR doesn't have any new classes.

**Review by jaadams5 — APPROVED** [review]
But I would like @gausie to do the push when the coverage/test question is resolved to their satisfaction.

**Comment by gausie** [comment]
> > Check out the coverage report, should be very easy to hit 100% on your two new classes
> 
> Which ones? This PR doesn't have any new classes.

I must have had two tabs, meant to comment this on the Consumables refactor.

**Pull request merged**
