### PR TITLE
detect use of Reanimator Wink At skill in a more generic manner

### PR DESCRIPTION
**Pull request by Malibu-Stacey**
When using the Comma Chameleon fed the flask of embalming fluid so it acts like the Reanimated Reanimator, the tracking for `_romanticFightsLeft` was off by one e.g.

```
Round 2: Malibu Stacey casts WINK AT!
Round 3: You point a finger at Wabrina, then at your opponent. Wabrina nods and begins calculating how much glow-juice he'll need to reanimate him.
You gain 76 Meat.
Preference _romanticFightsLeft changed from 0 to 2
```
followed by
```
Preference _romanticFightsLeft changed from 0 to -1
```
once the third and final wanderer is encountered.

### CODE REVIEW

**Review by jaadams5 — DISMISSED** [review]

**Review by gausie — CHANGES_REQUESTED** [review]
I'd rather explicitly test for either reanimator OR comma with reanimator. I think there's a function somewhere for like "is my familiar acting like so and so familiar"

EDIT:

Yes, I think changing the relevant bit to 
```java
 (KoLCharacter.getFamiliar().getEffectiveId() == FamiliarPool.REANIMATOR)
```
would do it

**Comment by Malibu-Stacey** [comment]
> I'd rather explicitly test for either reanimator OR comma with reanimator. I think there's a function somewhere for like "is my familiar acting like so and so familiar"
> 
> EDIT:
> 
> Yes, I think changing the relevant bit to
> 
> ```java
>  (KoLCharacter.getFamiliar().getEffectiveId() == FamiliarPool.REANIMATOR)
> ```
> 
> would do it

That's exactly what it is currently which doesn't appear to work.

**Comment by gausie** [comment]
> That's exactly what it is currently which doesn't appear to work.

No it isn't? Or am I misunderstanding.

**Comment by Malibu-Stacey** [comment]
Ah I missed the getEffectiveId() thing. Will change. Cheers @gausie.

**Review by gausie — APPROVED** [review]

**Pull request merged**
