### PR TITLE
In session log, note what clan we're switching to/are in

### PR DESCRIPTION
**Pull request by libraryaddict**
Currently there's no way to see when someone switches clans in the session log, this aims to correct that.

A potential extra feature could be detecting when you are booted from a clan, or leave the clan. But that's hardly a concern.

### CODE REVIEW

**Review by Veracity0 — APPROVED** [review]
This is fine.

**Comment by Veracity0** [comment]
> A potential extra feature could be detecting when you are booted from a clan, or leave the clan. But that's hardly a concern.

If you leave a ckan (and don't join another), that is interestig.

"Booted from a clan"?
That's even a thing? What kind of a dick do you have to be for that to happen?

Who cares?

**Review by jaadams5 — APPROVED** [review]

**Comment by Veracity0** [comment]
I'm going to stop approving PRs when my own PRs have been waiting longer for approval.
Which is to say, if my older PR needs approval, you can wait your turn.

**Comment by libraryaddict** [comment]
> I'm going to stop approving PRs when my own PRs have been waiting longer for approval. Which is to say, if my older PR needs approval, you can wait your turn.

That's fine, just remember I don't have the ability to approve PRs

**Pull request merged**
