### PR TITLE
Update items.txt

### PR DESCRIPTION
**Pull request by jaadams5**
autumn dollar is multiusable, but KoLmafia thought it was not
autumn leaf is multiusable, but KoLmafia thought it was not

I made the usual fix - changing usable to multiple and got a test error saying "multiple" is redundant for potions, so I just deleted usable instead.

### CODE REVIEW

**Review by gausie — COMMENTED** [review]
I believe many items were recently changed from usable to multiusable. Don't you need to actually add `multiple` here?

**Comment by jaadams5** [comment]
> I believe many items were recently changed from usable to multiusable. Don't you need to actually add `multiple` here?

Mafia reported "autumn dollar is multiusable, but KoLmafia thought it was not".  Changing "usable" to "mulitple" caused a file  integrity test to fail.  So removing "usable" should remove the "autumn dollar is multiusable, but KoLmafia thought it was not" message and allow the data file integrity test to pass.  The test failure message implied that potions were now, by definition, multiusable and thus potion, multiple was redundant.   Perhaps the test is wrong?

**Comment by jaadams5** [comment]
DataFileConsistencyTest,testPotions has the comments:
// All Potions And avatar potions are multiusable by default.
// Do not allow a redundant "multiple" attribute

Date is 7/22/2023

**Review by Veracity0 — APPROVED** [review]
That is the correct fix.

**Comment by gausie** [comment]
Great! I wasn't sure

**Pull request merged**
