### PR TITLE
Run gradle checks for pull requests.

### PR DESCRIPTION
**Pull request by heeheehee-kolmafia**
Among many other things, thiss will run spotlessCheck to make sure
that code has been properly formatted.

### CODE REVIEW

**Comment by gausie** [comment]
What are the other things that it will be amongst!

**Comment by heeheehee-kolmafia** [comment]
Hm, that's a good question. Apparently by default, it just runs tests, but it's a standard place for gradle plugin authors to insert additional checks (e.g. static analysis).

We should probably merge it with the test workflow.

**Comment by heeheehee-kolmafia** [comment]
(Done, by modifying the commit on this branch to make it clearer that it's a file rename.)

**Review by gausie — APPROVED** [review]
This is good, lets see how it looks on the existing PRs

**Pull request merged**
