### PR TITLE
Improvement for JS ecosystem

### PR DESCRIPTION
**Pull request by gausie**
Currently kolmafia can't be imported outside of a KoLmafia environment because ESM knows that the named exports aren't actually there. I would like to do this so I can share code between the web and a mafia script, knowing that I will not actually execute mafia-specific code. This fixes that

### CODE REVIEW

**Review by jaadams5 — DISMISSED** [review]
Not that I totally understand what is happening but I trust that it works and doesn't break anything "normal" KolMafia users use.

**Comment by gausie** [comment]
Without usage statistics I would imagine most KoLmafia users execute JS scripts at least once day, which this could affect if it were wrong.

**Comment by gausie** [comment]
Small mistake in the github action, I will push to main to fix.

**Comment by Veracity0** [comment]
> Without usage statistics I would imagine most KoLmafia users execute JS scripts at least once day, which this could affect if it were wrong.

I would be astonished if this were true.

Perhaps you mean "most KoLmafia users who are on Discord" - which I am sure is a minority of all KoLmafia users.

**Comment by gausie** [comment]
No I didn't mean that at all. I really just mean garbage-collector which is
frequently mentioned in in-game chat, moreso than any other script I see
referenced by name. But again, my anecdote and I could easily be wrong.
Just a comment in passing really.

**Comment by midgleyc** [comment]
Without usage statistics I expect most KoLmafia users don't execute any scripts at all.

**Pull request merged**
