### PR TITLE
Lock CoT / Bjorn familiars even if not worn.

### PR DESCRIPTION
**Pull request by heeheehee-kolmafia**
This was causing some incorrect maximizer behavior as reported by
phreddrickk.

https://kolmafia.us/threads/26413 for context.

### CODE REVIEW

**Review by jaadams5 — APPROVED** [review]
Looks reasonable.  I'll approve even thought the workflow isn't there yet.

**Comment by heeheehee-kolmafia** [comment]
So, I added this as a comment to the underlying commit, but I'll reproduce here:

Related, but technically not covered by the bug report:

In the bug, I noted that

    +100 bonus buddy bjorn, -tie

yields:

    bjornify (none) (+100)

Namely, instead of just equipping the dang bjorn, Maximizer suggests kicking out its current inhabitant. This is a similar fix -- just remove the hasEquipped requirement in the first place.

Thoughts?

**Comment by heeheehee-kolmafia** [comment]
@Rinn it looks like you tried to this previously a few months ago in https://github.com/kolmafia/kolmafia/commit/e53b4b54880a05368c496c77cc0beda5a7a03834 but backed it out in the next change because it wasn't consistent. Do you remember what you ran into?

**Comment by Rinn** [comment]
> @Rinn it looks like you tried to do this previously a few months ago in [e53b4b5](https://github.com/kolmafia/kolmafia/commit/e53b4b54880a05368c496c77cc0beda5a7a03834) but backed it out in the next change because it wasn't consistent. Do you remember what you ran into?

I think my issue was more from my change of trying to add a `bonus-carry` to give bonus value for carried familiar, and that had some problems.

**Comment by heeheehee-kolmafia** [comment]
> I think my issue was more from my change of trying to add a `bonus-carry` to give bonus value for carried familiar, and that had some problems.

I'll commit this upstream, then. Thanks.

**Comment by gausie** [comment]
This PR was automatically closed because we rebuilt the `main` branch on moving day. To reopen this PR:

1. Copy this branch
2. Hard reset this branch to `main`
3. Cherry pick your commits from your copy onto this branch
4. Hit "Reopen"!

**Pull request closed without merging**
