### PR TITLE
fix: bird of the day doesn't show up in maximizer

### PR DESCRIPTION
**Pull request by midgleyc**
Issue introduced in #1307.

The problem is that `getAllModifiers` checks `modifierStringsByName` for keys, but `overrideModifier` only modifies `modifiersByName`. So if we override a modifier that isn't in `modifiers.txt`, the maximizer won't see it.

I wrote the test in r26967 to confirm this was the issue, then fixed it.

### CODE REVIEW

**Review by gausie — APPROVED** [review]
Is `none` a thing or is that failing silently?

**Comment by gausie** [comment]
Can we show a warning if modify `modifiersByName` for something that's not in `modifierStringsByName`?

**Comment by midgleyc** [comment]
"none" is a thing. It's used in mutexes (and the scratch 'n' sniff weapons). It means "this has modifiers, but nothing material"

**Comment by midgleyc** [comment]
> Can we show a warning if modify modifiersByName for something that's not in modifierStringsByName?

We could, but I think the fact this is a problem indicates the data structure isn't right. Ideally (I think?) we want the keys to be the same. Perhaps it should be one object, which contains both the modifiers and a string, if we have a string.

Plus... I think most of our warnings just get ignored by the user. They're not really visible enough.

**Comment by midgleyc** [comment]
Will do a follow-up if I can get something working well.

I was hoping this same approach would make distillate show up in the maximizer, but it doesn't seem to.

**Comment by midgleyc** [comment]
I think the trick is actually that `getAllModifiersOfType` should be checking `modifiersByName`, not `modifierStringsByName`. From reading the file, the latter is "the contents of `modifiers.txt`" which never gets reset, whereas the former is "modifiers as they affect the current character", which does get reset.

Same for `getAllModifiers` which is only used by the `modifies` command, which I wasn't aware of.

**Comment by midgleyc** [comment]
Okay, we can't do that because we get an NPE. Presumably the modifiers are lazily loaded.

**Pull request merged**
