### PR TITLE
New TCRS dump from @chunkinaround

### PR DESCRIPTION
**Pull request by gausie**

### CODE REVIEW

**Comment by gausie** [comment]
Ah @midgleyc there seem to be issues with parsing damage for `Damage Aura` and `Thorns`

**Comment by midgleyc** [comment]
I think the fix is that we shouldn't be storing the damage we parse out of the KoL item description (or perhaps at all), but it is rather nice to see the potential items.

**Comment by midgleyc** [comment]
Also Turtle Tamer Vole has lost a bunch of items.

**Comment by midgleyc** [comment]
/also/ Knob Goblin encryption key has been renamed to Knob Goblin Encryption Key. When? Why? Who knows.

**Comment by gausie** [comment]
Getting 3bh to rerun it all rather than sort all these thorn and damage aura things manually

**Comment by gausie** [comment]
I checked in - @chunkinaround is abroad at the moment but will re run this when he gets back

**Comment by gausie** [comment]
I'll close this and open a new one when @chunkinaround can get us a new readout

**Pull request closed without merging**
