### PR TITLE
Write debug logs to a folder "debug" instead of root directory

### PR DESCRIPTION
**Pull request by libraryaddict**
Given the simplicity of this change, not sure a test should be added.
Regardless, did test the code and it works fine as expected.

### CODE REVIEW

**Comment by gausie** [comment]
Some explanation of why would be nice though!

**Comment by libraryaddict** [comment]
> Some explanation of why would be nice though!

If you're using the debug a lot, it fills up your root kolmafia folder with logs which looks messy.

**Comment by gausie** [comment]
"Using" debug is for developers, who are a very small group. Debug files are primarily for getting users to assist us in addressing unexpected errors. They're in the root directory so they can more easily be found by those users. Going to close this.

**Comment by midgleyc** [comment]
I agree with gausie with exactly the same reasoning!

**Comment by jaadams5** [comment]
agree++

**Pull request closed without merging**
