### PR TITLE
typo

### PR DESCRIPTION
**Pull request by fredg1**

### CODE REVIEW

**Comment by jaadams5** [comment]
where are telescope6 and 7 actually used in the code?  I can't find them.  They aren't in any of my settings so if if you have them it is presumably because of a script or code that has not been committed yet.

**Comment by fredg1** [comment]
> where are telescope6 and 7 actually used in the code? I can't find them. They aren't in any of my settings so if if you have them it is presumably because of a script or code that has not been committed yet.

They're used indirectly, by concatenation

TelescopeRequest.java, line 128
`      String setting1 = "telescope" + upgrades;`

**Comment by gausie** [comment]
Nah just remove 'em. It's impossible for them to have a value, right? So the default return of "" is correct for them (in case someone is still using them erroneously).

As long as `telescopeUpgrades` is not affected, I think we're good.

**Review by jaadams5 — APPROVED** [review]
Seriously?  ;-)

**Comment by gausie** [comment]
Oh @fredg1 I would have removed the abiltiy for them to be set too in that loop!

**Pull request merged**
