### PR TITLE
Gift shop ignores trouser discounts

### PR DESCRIPTION
**Pull request by libraryaddict**
Easily tested by attempting to buy an item from gift shop, but the trouser discount doesn't apply.

5 finger discount still seems to apply.

### CODE REVIEW

**Comment by Veracity0** [comment]
Both trousers?

**Comment by libraryaddict** [comment]
> Both trousers?

Huh good question.

Designer sweatpants doesn't, but I can't test travoltan trousers. It might work with those, might not. I can't test.

**Comment by Veracity0** [comment]
I can answer this. Today was day two of a Hardcore Kingdom of Exploathing run - but I completed it. (!)

I pulled Travoltan trousers.
I have the Five Finger Discount skill.

- No trousers, a black lotus is 95,000 (discounted from 100,000)
- designer sweatpants, a black lotus is 95,000 (discounted from 100,000)
- Travoltan trousers, a black lotus is 90,000 (discounted from 100,000)

According to item description, Travoltan trousers have the "5-Finger Discount" enchantment.
According to the Wiki: "The 5% discount applies to items from [the Gift Shop](https://kol.coldfront.net/thekolwiki/index.php/The_Gift_Shop) but not to packages there."

**Comment by Veracity0** [comment]
Here is the full relevant text from the Wiki:

> - As stated in the Mr. Store description, the "5-Finger Discount" enchantment equates to a 5% discount at [NPC stores](https://kol.coldfront.net/thekolwiki/index.php/Category:NPC_Stores).
-- The 5% discount doesn't work in the [Trophy Hut](https://kol.coldfront.net/thekolwiki/index.php/Trophy_Hut) or [The Raffle House](https://kol.coldfront.net/thekolwiki/index.php/The_Raffle_House). It also cannot be used at [The Hippy Store](https://kol.coldfront.net/thekolwiki/index.php/The_Hippy_Store) (pre-quest), or [The Bugbear Bakery](https://kol.coldfront.net/thekolwiki/index.php/The_Bugbear_Bakery) as these stores require specific outfits to be worn, all of which include pants. Until the Cobb's Knob revamp, the [The Cobb's Knob Laboratory](https://kol.coldfront.net/thekolwiki/index.php/Laboratory) required an outfit with pants but no longer does.
-- The 5% discount applies to items from [the Gift Shop](https://kol.coldfront.net/thekolwiki/index.php/The_Gift_Shop) but not to packages there.
-- The discount applies to [Doc Galaktik's](https://kol.coldfront.net/thekolwiki/index.php/Doc_Galaktik%27s_Medicine_Show) items, but not to his [Restoratives](https://kol.coldfront.net/thekolwiki/index.php/Doc_Galaktik%27s_Medicine_Show#Restoratives_on_Tap).
-- The discount does not work in stores that do not use meat, such as [The Bounty Hunter Hunter's Shack](https://kol.coldfront.net/thekolwiki/index.php/The_Bounty_Hunter_Hunter%27s_Shack), [Big Brother](https://kol.coldfront.net/thekolwiki/index.php/Big_Brother), or [The Crimbo Cartel](https://kol.coldfront.net/thekolwiki/index.php/The_Crimbo_Cartel).

How do the designer sweatpants compare for:
- Trophy Hut
- Raffle House
- Doc Galaktik's

(The stores that require outfits with pants and with stores that don't use Meat are sort of a Duh.)

**Comment by horrible-little-slime** [comment]
This inconsistency might be worth an in-game bug report

**Comment by Veracity0** [comment]
I did testing.

- Doc Galaktik has changed since the Wiki wrote that. Both kinds of trousers give a discount to every item in his store.
- Neither kind of trousers gives a discount at the Raff;e House
- (I do not qualify for trophies)
- Travoltan trousers give a discount for gifts but not gift packages
- designer sweatpants do not give a discount for either.

Given that, I think the Travoltan trousers are unambiguously superior, if you have both. :)

I recommend changing:
```
  private static final Set<AdventureResult> DISCOUNT_TROUSERS =
      List.of(ItemPool.get(ItemPool.TRAVOLTAN_TROUSERS), ItemPool.get(ItemPool.DESIGNER_SWEATPANTS));
```
to
```
  private static final List<AdventureResult> DISCOUNT_TROUSERS =
      List.of(ItemPool.get(ItemPool.TRAVOLTAN_TROUSERS), ItemPool.get(ItemPool.DESIGNER_SWEATPANTS));
```
in NPCPurchase request, so that 
```
  private static AdventureResult getEquippableTrousers() {
    return DISCOUNT_TROUSERS.stream()
        .filter(KoLConstants.inventory::contains)
        .filter(EquipmentManager::canEquip)
        .findFirst()
        .orElse(null);
  }
```
will prefer them, if you have both.

I also recommend changing ```KoLConstants.inventory::contains``` to ```InventoryManager::hasItem``` to look in all "accessible" places - like storage after Ronin. EquipmentRequest will do InventoryManager.retrieveItem to pull them, if necessary.

**Review by Veracity0 — APPROVED** [review]
Looks good.

**Pull request merged**
