### PR TITLE
Add Crimbo24 Bar, Cafe, and Factory

### PR DESCRIPTION
**Pull request by Veracity0**

### CODE REVIEW

**Comment by midgleyc** [comment]
Thanks for making these!

lucky moai statuette is 50 easter + 50 patrick -- it looks like you have it as only Easter?

It also looks likely the final entry in both the cafe and bar will involve all the currencies.

**Comment by Veracity0** [comment]
Oh, my. I hadn't noticed that.
Things with multiple currencies need to be creation methods, rather than coinmasters.
Let me ponder this.

**Comment by Veracity0** [comment]
Yeah.
```
<tr rel="11771">
  <td valign=center><input type=radio name=whichrow value=1538></td>
  <td><img src="/images/itemimages/chiatiki.gif" class="hand pop"
  rel="desc_item.php?whichitem=232982896"
           onClick='javascript:descitem(232982896)'></td>
  <td valign=center><a onClick='javascript:descitem(232982896)'><b>lucky moai statuette</b>&nbsp;&nbsp;&nbsp;&nbsp;</a></td>
  <td>
    <img src=/images/itemimages/spirit_easter.gif width=30 height=30 onClick='javascript:descitem(756560474)' alt="Spirit of Easter" title="Spirit of Easter"></td>
  <td><b>50</b>&nbsp;&nbsp;</td>
  <td>
    <img src=/images/itemimages/spirit_stpatrick.gif width=30 height=30 onClick='javascript:descitem(655322653)' alt="Spirit of St. Patrick's Day" title="Spirit of St. Patrick's Day"></td>
  <td><b>50</b>&nbsp;&nbsp;</td>
  <td></td>
  <td>&nbsp;&nbsp;</td>
  <td></td>
  <td>&nbsp;&nbsp;</td>
  <td></td>
  <td>&nbsp;&nbsp;</td>
  <td valign=center>
    <input class="button doit multibuy "  type=button rel='shop.php?whichshop=crimbo24_factory&action=buyitem&quantity=1&whichrow=1538&pwd=daa2136bd0601e7e4671281b3354bd48' value='Buy'></td>
</tr>
```

I observe we can learn new items:
- the ```<tr rel="1771">``` has the item number.
- first td has a whichrow
- the next td has an image has the descid and image
- the next td has a bold item name and the same descid
- There are then 5 pairs of tds:
-- a bold number
-- a currency with image descid, and item name
- finally, a td with a button.

I'll write a parser for that and see how the General Store, Grandma, and other shop.phps look.

**Comment by Veracity0** [comment]
Hah.

Here is the Armory and Leggery with some pulverized standard rewards:

```
<tr rel="11025">
  <td valign=center></td>
  <td>
    <img src="https://d2uyhvukfffg5a.cloudfront.net/itemimages/cerarobe.gif" class="hand pop" rel="desc_item.php?whichitem=935849680" onClick='javascript:descitem(935849680)'></td>
  <td valign=center><a onClick='javascript:descitem(935849680)'><b>ceramic cenobite's robe</b>&nbsp;&nbsp;&nbsp;&nbsp;</a></td>
  <td><img src=https://d2uyhvukfffg5a.cloudfront.net/itemimages/adobebits.gif width=30 height=30 onClick='javascript:descitem(469007963)' alt="adobe assortment" title="adobe assortment"></td>
  <td><b>1</b>&nbsp;&nbsp;</td>
  <td></td>
  <td>&nbsp;&nbsp;</td>
  <td></td>
  <td>&nbsp;&nbsp;</td>
  <td></td>
  <td>&nbsp;&nbsp;</td>
  <td></td>
  <td>&nbsp;&nbsp;</td>
  <td valign=center><input class="button doit multibuy "  type=button rel='shop.php?whichshop=armory&action=buyitem&quantity=1&whichrow=1453&pwd=daa2136bd0601e7e4671281b3354bd48' value='Buy'></td>
</tr>
```
That does not have radio buttons in front of each item and a "Buy Item" box at the bottom.

And here is Grandma:

```
<tr rel="4283">
  <td valign=center><input type=radio name=whichrow value=125></td>
  <td>
    <img src="https://d2uyhvukfffg5a.cloudfront.net/itemimages/tailpiece.gif" class="hand pop" rel="desc_item.php?whichitem=219864306" onClick='javascript:descitem(219864306)'></td>
  <td valign=center><a onClick='javascript:descitem(219864306)'><b>crappy Mer-kin tailpiece</b>&nbsp;&nbsp;&nbsp;&nbsp;</a></td>
  <td>
    <img src=https://d2uyhvukfffg5a.cloudfront.net/itemimages/seachaps.gif width=30 height=30 onClick='javascript:descitem(424923166)' alt="sea chaps" title="sea chaps"></td>
  <td><b>1</b>&nbsp;&nbsp;</td>
  <td>
    <img src=https://d2uyhvukfffg5a.cloudfront.net/itemimages/teflonfins.gif width=30 height=30 onClick='javascript:descitem(667590304)' alt="teflon swim fins" title="teflon swim fins"></td>
  <td><b>1</b>&nbsp;&nbsp;</td>
  <td>
    <img src=https://d2uyhvukfffg5a.cloudfront.net/itemimages/scale3.gif width=30 height=30 onClick='javascript:descitem(922469052)' alt="pristine fish scale" title="pristine fish scale"></td>
  <td><b>3</b>&nbsp;&nbsp;</td>
  <td></td>
  <td>&nbsp;&nbsp;</td>
  <td></td>
  <td>&nbsp;&nbsp;</td>
  <td valign=center><input class="button doit multibuy disabled" disabled type=button rel='shop.php?whichshop=grandma&action=buyitem&quantity=1&whichrow=125&pwd=daa2136bd0601e7e4671281b3354bd48' value='Buy'></td>
</tr>
```
That does have radio buttons.

**Review by jaadams5 — DISMISSED** [review]

**Comment by Veracity0** [comment]
I can now parse shop texts into ItemRow objects.

```
> test load test_shop_crimbo23_pirate_armory.html

Read 18,003 bytes into a 18,003 character string

> test itemrows

shop 'Crimbuccaneer Junkworks' offers 5 items.
row = 1420 item = Crimbuccaneer flotsam (3)
cost: sawed-off blunderbuss
row = 1418 item = Crimbuccaneer flotsam (3)
cost: Crimbuccaneer shirt
row = 1422 item = Crimbuccaneer flotsam (3)
cost: pegfinger
row = 1421 item = Crimbuccaneer flotsam (3)
cost: shipwright's hammer
row = 1417 item = Crimbuccaneer premium booty sack
cost: Crimbuccaneer flotsam (200)

> test load test_shop_crimbo24_factory.html

Read 16,291 bytes into a 16,291 character string

> test itemrows

shop 'Crimbo Factory' offers 3 items.
row = 1538 item = lucky moai statuette
cost: Spirit of Easter (50)
cost: Spirit of St. Patrick's Day (50)
row = 1533 item = Secrets of the Master Egg Hunters
cost: Spirit of Easter (500)
row = 1534 item = How to Lose Friends and Attract Snakes
cost: Spirit of St. Patrick's Day (500)
```

I have 4 test files: Armory & Leggery, Grandma, Crimbo24 Factory, and Crimbo23 Pirate Armory, which test different things. I'll write up some tests for that object.

Then:

parsing coinmasters.txt into those objects
making Coinmasters work with them
inventing a syntax for that file to allow multiple ingredients
making coinmasters work with such
and printing newly discovered coinmaster.txt entries in the new format

Just a simple matter of coding. :)

**Review by jaadams5 — DISMISSED** [review]
I'll approve but it doesn't seem like ShopRowTest is finished.  But in the spirit of having new Crimbo content supported during Crimbo that can wait.

**Review by jaadams5 — APPROVED** [review]

**Comment by Veracity0** [comment]
OK, I am ready to make a release for this.

I can parse shop.php and generate coinmaster entries using a new ShopRow format.
I have those entries in coinmasters.txt - commented out.
I have Coinmasters to handle the bar, cafe and factory - but since the entries are commented out, they can't trade
Visiting the shop identified unknown items and printed them, as before. I have added those items.

So, now, if you visit the Crimbo24 shops, you get logging about coinmaster entries.

I think it is worth releasing this into the wild now - in particular because it has updated data files to include everything we know so far. (not including Thanksgiving Island monsters or Colonel Brando.

To finish the coinmasters:

- parse the new-style entries into ShopRow objects
- coinmasters can use those instead of buyItems and sellItems.
- This will allow multiple currencies to be used to purchase items.
This is a fair amount of work, but it depends on everything in this PR, which I think is solid.

**Review by jaadams5 — APPROVED** [review]

**Comment by midgleyc** [comment]
Merged with trust the outstanding items will be completed :)

**Comment by midgleyc** [comment]
ref follow-up: relates #2566, relates #2570

**Pull request merged**
