### PR TITLE
Language Server - location tests base

### PR DESCRIPTION
**Pull request by fredg1**
preliminary additions to textui in order to start submitting the other patches

### CODE REVIEW

**Comment by fredg1** [comment]
(note: This PR is very much ready and waiting for review.
It's just that I'm making further PRs on my side in the meantime,
and am sending content shared between many of them this way.

**Comment by jaadams5** [comment]
I tried to review.  I either need more context or we need someone else.  Two things that bothered me.  One is a comment that says TEMPORARY.  At the very least the comment should say why it is temporary and what event (in code development) will make it permanent or can be deleted.  Some systems support an annotation "at ToDo"  (don't know how to escape here) that at least will be flagged and can nag a dev about something they need to address.  The other is I'm not sure I agree with the name or location of test.../ScriptData but it does appear that someone else approved that so my agreement is not needed for a review.

For my information why did you choose to introduce yet another dependency for testing?

**Comment by fredg1** [comment]
> 
> 
> One is a comment that says TEMPORARY. At the very least the comment should say why it is temporary and what event (in code development) will make it permanent or can be deleted. Some systems support an annotation "at ToDo" (don't know how to escape here) that at least will be flagged and can nag a dev about something they need to address. 


https://github.com/kolmafia/kolmafia/pull/49#pullrequestreview-787980812 should provide some context.
Basically, https://github.com/kolmafia/kolmafia/pull/49 is too big/touches too many classes for it to be reviewed all at once. So instead, I agreed to split it into multiple PRs, each of them addressing a specific parsetree class (or a closely related group), and coming with tests.
Once this PR is merged, I'll start submitting some of them (I can't submit them all at once, because some of them have conflicts in the tests, or are dependant on another).

The "TEMPORARY" are constructors that will be removed by then end of all this (since the goal is to give everything a Location). They are constructors that only exist because of how I can't submit the whole change at once.

> 
> 
> For my information why did you choose to introduce yet another dependency for testing?

See https://github.com/kolmafia/kolmafia/pull/204/commits/76b91c53880e5ccac47152ef9348f79f40112fe5 's commit message.

**Review by jaadams5 — APPROVED** [review]

**Review by jaadams5 — DISMISSED** [review]
You answered my questions so I will approve even if I am not completely certain what is going on :-)  You will, however solemnly promise to remove the TEMPORARY code ASAP.  I merge tomorrow if no one else beats me to it.

**Comment by fredg1** [comment]
> 
> 
> You answered my questions so I will approve even if I am not completely certain what is going on :-) You will, however solemnly promise to remove the TEMPORARY code ASAP. I merge tomorrow if no one else beats me to it.

I solemnly swear it. The incoming patches all target the addition of locations, and the temporary constructors will be removed as soon as they no longer get called.

**Review by jaadams5 — APPROVED** [review]

**Pull request merged**
