### PR TITLE
Fix isEmpty() not a method on StringBuilders

### PR DESCRIPTION
**Pull request by gausie**
Everything seems to suggest that its just my computer on which this fails? Because this function is covered by the tests. But still, I need this fix to run mafia now.

### CODE REVIEW

**Comment by heeheehee-kolmafia** [comment]
StringBuilder derives isEmpty from CharSequence, which got the method in Java 15. How did this pass our build before?

**Review by heeheehee-kolmafia — APPROVED** [review]

**Comment by gausie** [comment]
It means I must have messed up something in my GitHub workflow change to get separate version checks to happen concurrently

**Comment by heeheehee-kolmafia** [comment]
Indeed.

From check logs from the Actions tab:
```
 Run Checks (ubuntu-latest, 11)
succeeded 6 minutes ago in 2m 48s
...
Run actions/setup-java@v2
Resolved Java 17.0.1+12 from tool-cache
Setting Java 17.0.1+12 as the default

Java configuration:
  Distribution: temurin
  Version: 17.0.1+12
  Path: /opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/17.0.1-12/x64
```

**Comment by Veracity0** [comment]
Well, darn it!

**Pull request merged**
