### PR TITLE
Update canAdventure detection for level 2 of spookyraven manor

### PR DESCRIPTION
**Pull request by gausie**
Turns out checking for ghost of a necklace isn't quite right - it's not a quest item so (for example) in a casual run you may have hundreds of them on hand but still not have unlocked the second floor of the manner.

I think this covers it but it is untested

### CODE REVIEW

**Comment by gausie** [comment]
Also @Veracity0 looking through this made me realise that there's a lot of overlap between the canAdventure code and the QuestManager - if you look at QuestManagerTest we're sort of doing a lot of these already (and we certainly already have test files for many of these interactions!)

**Comment by Veracity0** [comment]
"Lady Spookyraven's necklace" is the quest item you get from the 5th writing desk.
If you have it in inventory, you have not talked to her yet and have not completed the quest.
If you talk to her, that completes the quest - and she gives you the ghost necklace.

If you have Lady Spookyraven's necklace, we need to talk to her to complete the necklace quest.
If, having done that, we have not talked to her on the second floor yet, we need to do so in order to start the dancing quest and open the second floor rooms.

It appears that your code is throwing away handling Lady Spookyraven's necklace in favor of the ghost necklace.
That is backwards.

**Comment by gausie** [comment]
> "Lady Spookyraven's necklace" is the quest item you get from the 5th writing desk. If you have it in inventory, you have not talked to her yet and have not completed the quest. If you talk to her, that completes the quest - and she gives you the ghost necklace.
> 
> If you have Lady Spookyraven's necklace, we need to talk to her to complete the necklace quest. If, having done that, we have not talked to her on the second floor yet, we need to do so in order to start the dancing quest and open the second floor rooms.
> 
> It appears that your code is throwing away handling Lady Spookyraven's necklace in favor of the ghost necklace. That is backwards.

You're right I must have got confused writing this code. I'll close the PR

**Comment by Veracity0** [comment]
> there's a lot of overlap between the canAdventure code and the QuestManager - if you look at QuestManagerTest we're sort of doing a lot of these already (and we certainly already have test files for many of these interactions!)

KoLAdventureValidationTest tests canAdventure and prepareForAdventure. In doing so, it sometimes completes quests. The tests sometimes validate that quests have advanced - just as QuestManagerTest does - but also, always, verifies that canAdventure and/or prepareForAdventure pass - and that the requests submitted by the latter are exaclty those needed to advance the quests. I think you mean that the existing responseTexts would be useful for the latter.

**Review by Veracity0 — APPROVED** [review]

**Pull request merged**
