### PR TITLE
Fix array_rand extra rolls.

### PR DESCRIPTION
**Pull request by phulin**
The array_rand implementation in PHPRandom fails to short circuit after reaching the desired number of elements, which causes extra rolls to be drawn from the RNG. While the first result matches, future array_rand calls will be out of sync.

### CODE REVIEW

**Comment by gausie** [comment]
> Context as to why this is needed? Any chance of a test that fails without this?

I mean if there is a bug in existing code I don't think context is necessarily needed.

**Comment by jaadams5** [comment]
> I mean if there is a bug in existing code I don't think context is necessarily needed.

Given the absence of code documentation, what's the bug?  Is it an array indexing issue that is reported elsewhere that I have not seen or is it something downstream isn't working because the random number generator is called too many times or what?  What bad thing happens if this is not fixed?

**Comment by gausie** [comment]
> > I mean if there is a bug in existing code I don't think context is necessarily needed.
> 
> Given the absence of code documentation, what's the bug? Is it an array indexing issue that is reported elsewhere that I have not seen or is it something downstream isn't working because the random number generator is called too many times or what? What bad thing happens if this is not fixed?

I agree, I want to see a test to confirm that it is a bug. But I don't need context on why a bug needs fixing once it's confirmed to be such.

**Comment by jaadams5** [comment]
Maybe "context" wasn't the best way to ask "what is the bug?"  If that is answered then how it was discovered is just satisfying curiosity.

**Comment by phulin** [comment]
Sorry, I pushed this this morning and then got distracted. I updated the description and will write a test.

**Review by midgleyc — APPROVED** [review]
Thanks!

**Pull request merged**
