### PR TITLE
refactor: use instanceof patterns where detected

### PR DESCRIPTION
**Pull request by midgleyc**
I am slightly annoyed every time I see a cast, so mass-convert to instanceof patterns where obvious.

Done automatically by IDE on the first commit and manually on the second.

### CODE REVIEW

**Comment by jaadams5** [comment]
> I am slightly annoyed every time I see a cast, so mass-convert to instanceof patterns where obvious.
> 

Have you considered some anger management counseling?

> Done automatically by IDE on the first commit and manually on the second.

Which IDE and if IntelliJ IDEA Community Edition what setting turns it on and off?

**Comment by midgleyc** [comment]
> Have you considered some anger management counseling?

No, I think counseling is about how you react to what you feel, instead of managing to not have the feelings in the first place.

> Which IDE and if IntelliJ IDEA Community Edition what setting turns it on and off?

Yes, IntelliJ. Inspections -> Java -> Java language level migration aids -> Java 16 -> Pattern variable can be used.

**Comment by jaadams5** [comment]
> No, I think counseling is about how you react to what you feel, instead of managing to not have the feelings in the first place.

"annoy" has been a trigger word in the past.

> Yes, IntelliJ. Inspections -> Java -> Java language level migration aids -> Java 16 -> Pattern variable can be used.

Thanks.  In theory it should be flagged for me as well and I have not seen it.  I know there was at least one instance because the opportunity was pointed out in a review.

**Review by jaadams5 — APPROVED** [review]
Trusting you and the IDE ;-)  (but I really did look at everything).

**Pull request merged**
