### PR TITLE
Throw JS exceptions when passing null / undefined to ASH.

### PR DESCRIPTION
**Pull request by heeheehee-kolmafia**
I threw this commit together a few weeks ago and totally forgot about it.

Still needs tests, but posting as a draft PR in case someone else wants to tinker further.

### CODE REVIEW

**Comment by heeheehee-kolmafia** [comment]
Note that I'm using EvaluatorException so it can actually be caught in JS. This is quite possibly an abuse of the API.

**Comment by heeheehee-kolmafia** [comment]
That said, the reason I did it that way was so it would actually catch null / undefined that was nested deeper within some object structure. We'll want to get that working before we merge this PR.

**Review by gausie — COMMENTED** [review]
Can you add a check to confirm that nulls/undefineds in arrays and objects are fine throughout your code, just not when relayed to the ASH environment. And perhaps update the error message to reflect that?

**Comment by heeheehee-kolmafia** [comment]
> Can you add a check to confirm that nulls/undefineds in arrays and objects are fine throughout your code, just not when relayed to the ASH environment. And perhaps update the error message to reflect that?

Done on both fronts.

Technically the `js` CLI command can represent these types, as the existing tests had demonstrated, but it seems simpler to have uniform enforcement. (We can still print null / undefined at this time. I think adding logic to ban that as well in the interest of uniformity would have so many unintended consequences that it's not worthwhile -- JS functions without explicit return values will return `undefined`, after all)

**Comment by gausie** [comment]
I will try to run some big JS scripts with this branch and then merge if all looks ok.

**Comment by gausie** [comment]
This has worked with all my nonsense for three days, merging.

**Pull request merged**
