### PR TITLE
Time-Twitching Tower: Primordial Soup

### PR DESCRIPTION
**Pull request by gausie**
This covers skeleton as well as support for the extra familiar weight from the soups.

After this PR we need to (at least):
- Apply modifiers/something for whatever it is the soup attributes do
- Support the evolving organism
- Add a line whatever last rare there is when someone finds it
- Update familiar info on consuming soup as well as visiting familiar.php

### CODE REVIEW

**Comment by Veracity0** [comment]
No Coinmaster? I went to check a couple hours ago and the TTT was not there.
I checked again and it is there - and the Primordial Soup Kitchen could be a Coinmaster for the unevolved soups - but needs to be a mixing method for the evolved soups.

**Comment by gausie** [comment]
Oh yes, good point. We need the coinmaster for sure.

**Review by midgleyc — APPROVED** [review]
Add for skeleton, just in time for the tower to disappear and be untestable ;)

**Comment by Veracity0** [comment]
> Oh yes, good point. We need the coinmaster for sure. But I won't do in this PR
@gausie @midgleyc 

Part of the difficulty is that the Primordial Soup Kitchen has multiple recipes for the same item
Also, the recipes take multiple ingredients, which we (until recently) had to do via mixing method.
.
That's an issue in general with concoctions, shops, creation methods; we map itemId to a single recipe.

I have a Draft PR open to investigate this.
I also implemented ShopRow-style coinmasters - foruse in the Crimbo24 shops - which allow multiple ingredient coinmasters.

Here is how I represent this shop in coinmasters.txt:

```
The Primordial Soup Kitchen	ROW1491	bacteria bisque	Chroner (10)
The Primordial Soup Kitchen	ROW1492	ciliophora chowder	Chroner (10)
The Primordial Soup Kitchen	ROW1493	cream of chloroplasts	Chroner (10)	
The Primordial Soup Kitchen	ROW1499	elbow soup	bacteria bisque	protogenetic chunklet (elbow)
The Primordial Soup Kitchen	ROW1498	elbow soup	ciliophora chowder	protogenetic chunklet (elbow)
The Primordial Soup Kitchen	ROW1497	elbow soup	cream of chloroplasts	protogenetic chunklet (elbow)
The Primordial Soup Kitchen	ROW1502	flagellate soup	bacteria bisque	protogenetic chunklet (flagellum)
The Primordial Soup Kitchen	ROW1500	flagellate soup	ciliophora chowder	protogenetic chunklet (flagellum)
The Primordial Soup Kitchen	ROW1501	flagellate soup	cream of chloroplasts	protogenetic chunklet (flagellum)
The Primordial Soup Kitchen	ROW1496	lip soup	bacteria bisque	protogenetic chunklet (lips)
The Primordial Soup Kitchen	ROW1495	lip soup	ciliophora chowder	protogenetic chunklet (lips)
The Primordial Soup Kitchen	ROW1494	lip soup	cream of chloroplasts	protogenetic chunklet (lips)
The Primordial Soup Kitchen	ROW1505	muscular soup	bacteria bisque	protogenetic chunklet (muscle)
The Primordial Soup Kitchen	ROW1504	muscular soup	ciliophora chowder	protogenetic chunklet (muscle)
The Primordial Soup Kitchen	ROW1503	muscular soup	cream of chloroplasts	protogenetic chunklet (muscle)
The Primordial Soup Kitchen	ROW1508	synaptic soup	bacteria bisque	protogenetic chunklet (synapse)
The Primordial Soup Kitchen	ROW1507	synaptic soup	ciliophora chowder	protogenetic chunklet (synapse)
The Primordial Soup Kitchen	ROW1506	synaptic soup	cream of chloroplasts	protogenetic chunklet (synapse)
```

If I implemented this coinmaster, you could see all the recipes in the CoinmasterFrame and select which one you wanted.

Unfortunately, I am missing one datum to be able to implement it: shop.php?whichshop=XXXXX

If you can tell me XXXXX - or, even better, supply an HTML file of visiting the Primordial Soup Kitchen - I will (trivially) implement the coinmaster and we will be ready when Twitch opens again.
If ever.

**Pull request merged**
