### PR TITLE
refactor: use default github token for junit report

### PR DESCRIPTION
**Pull request by midgleyc**
JUnit report seems broken after the latest update. Going to try a few things that might fix it.

### CODE REVIEW

**Comment by midgleyc** [comment]
Progress:
* neither the default token, not the custom token for me, work in publishing results
* the custom token doesn't seem to exist in the secrets
* the custom token does work for some people: e.g. it worked here: https://github.com/kolmafia/kolmafia/actions/runs/2885651235
* post-3.3.0, if the custom token fails it crashes...
* ...even if publishing the job summary is disabled

I've reported https://github.com/mikepenz/action-junit-report/issues/640 but this whole thing is quite odd.

**Comment by mikepenz** [comment]
Looking into: `https://github.com/kolmafia/kolmafia/actions/runs/2885651235` -> this was still run with v3.2.0 of the action.

**Comment by mikepenz** [comment]
Looking for `Resource not accessible by integration` specifically also highlights mostly token permissions scope problems:
- https://github.com/orgs/community/discussions?discussions_q=Resource+not+accessible+by+integration
- https://github.com/actions/first-interaction/issues/10

**Comment by midgleyc** [comment]
Fixed action after discussion.

**Pull request closed without merging**
