### PR TITLE
Lowercase the topic when consulting grandpa

### PR DESCRIPTION
**Pull request by libraryaddict**
Noticed twinkle vision pref didn't update when I used a capitalized topic, despite grandpa still talking about it.

### CODE REVIEW

**Comment by gausie** [comment]
By this logic there could be a behaviour that requires using capital
letters that would then be impossible to submit via mafia.

Make a big report to KoL I think.

**Comment by libraryaddict** [comment]
@gausie I don't follow. kol behaves properly, but mafia isn't setting the twinkle vision preference because I used "Hierfal" instead of "hierfal"

**Comment by jaadams5** [comment]
I noticed that the preference was not set for me when I asked about "Hierfal" as well.  There is precedent for assuming user input is case insensitive in which case this fix is reasonable.  If it is possible, likely, or currently true that the Grandpa topics could be case sensitive on KOL's side then this fix could introduce a problem in the future and changing the switch to trigger on "Hierfal" would be a better fix.

**Comment by gausie** [comment]
Oh! Totally misunderstood. This is good then.

**Review by jaadams5 — DISMISSED** [review]

**Review by midgleyc — APPROVED** [review]

**Pull request merged**
