### PR TITLE
formatting errors caused by end-of-line comments

### PR DESCRIPTION
**Pull request by fredg1**
I can't assert that I definitely got everything; VScode was *really* not cooperative with this...

### CODE REVIEW

**Comment by jaadams5** [comment]
What does this do that gradlew spotlessapply didn't?

**Comment by heeheehee-kolmafia** [comment]
From a quick skim, spotless doesn't want to move comments relative to code. So, for instance,

```
if (someCondition)
// here's a comment
{
...
}
```

will not get reformatted as
```
if (someCondition) {
  // here's a comment
  ...
}
```

**Review by jaadams5 — COMMENTED** [review]
Have you built and then run a few turns with a character with these changes?  I'll approve when the answer is yes but the Merge will happen sooner of someone else makes that check.

**Comment by fredg1** [comment]
I haven't...

**Comment by jaadams5** [comment]
> I haven't...

Would you consider doing so or does this wait until someone else gets around to it?

:-)

**Comment by fredg1** [comment]
I can give it a go. What exactly am I supposed to be looking for, other than a sudden debug log?

**Comment by jaadams5** [comment]
> I can give it a go. What exactly am I supposed to be looking for, other than a sudden debug log?

That and just something that does not work as you expect it to.  I have found changes that stopped the app from starting, stopped windows from updating or displaying, scripts that didn't run, etc.  I'm not expecting any issues but with 30 files changed and two of us thinking nothing should change, actually building and burning turns increases confidence in the patch.

**Comment by fredg1** [comment]
Lot of errors all right... but this branch was based off of 25831, i.e. right before https://github.com/kolmafia/kolmafia/pull/181...
Let's pull from upstream and retry...

**Comment by fredg1** [comment]
Way better now~~
Nothing to report.

**Review by jaadams5 — APPROVED** [review]

**Pull request merged**
