### PR TITLE
Fix name mismatches in encounters.txt.

### PR DESCRIPTION
**Pull request by phulin**
#2459 had some mismatches between encounters.txt and adventures.txt, which caused error messages on opening mafia and for some encounters to fail to load.

### CODE REVIEW

**Comment by gausie** [comment]
Can you add a regression check for this in DataFileConsistencyTest too?

**Comment by gausie** [comment]
Yeah that works too, though shifts some of the checks onto runtime instead of CI time. I think that's fine.

**Review by midgleyc — CHANGES_REQUESTED** [review]
considering this happened, please add something in DataFileConsistencyTest

**Comment by midgleyc** [comment]
I see that what you've got technically tests it, but if somebody adds a lot of data in the future, they'll have to debug to find which lines fail, whereas with a normal test they could just run the test and know the lines, so I'd prefer that please.

**Review by midgleyc — APPROVED** [review]

**Comment by midgleyc** [comment]
Much appreciated!

**Pull request merged**
