### PR TITLE
Fix JSON.stringify for enumerated value

### PR DESCRIPTION
**Pull request by gausie**
- Make JSON.stringify work on enumerated values and ensure that keys are camel cased as expected
- Add tests

### CODE REVIEW

**Comment by midgleyc** [comment]
Something odd seems to be happening:

```
> js var x = JSON.stringify(Item.get("lime")); var y = JSON.parse(x); typeof y

Returned: string
```
and y.image is null, but

```
> js var x = "{\"gift\":false,\"seller\":\"none\",\"maxhp\":0,\"cookable\":true,\"noobSkill\":\"Small Intestine\",\"fancy\":false,\"plural\":\"limes\",\"notes\":\"\",\"discardable\":true,\"minmp\":0,\"descid\":\"839503923\",\"candy\":false,\"moxie\":\"0\",\"combatReusable\":false,\"fullness\":1,\"tcrsName\":\"lime\",\"recipe\":\"none\",\"combat\":false,\"mixable\":true,\"inebriety\":0,\"quest\":false,\"multi\":false,\"usable\":false,\"candyType\":\"none\",\"muscle\":\"0\",\"skill\":\"none\",\"mysticality\":\"0\",\"tradeable\":true,\"id\":333,\"adventures\":\"2\",\"image\":\"lime.gif\",\"potion\":false,\"spleen\":0,\"levelreq\":2,\"maxmp\":0,\"minhp\":0,\"smallimage\":\"lime.gif\",\"quality\":\"decent\",\"reusable\":false,\"buyer\":\"none\",\"pasteable\":true,\"nameLength\":4,\"name\":\"lime\",\"smithable\":false,\"dailyusesleft\":15,\"chocolate\":false}"; var y = JSON.parse(x); y.image

Returned: lime.gif
```

but my other test
```
> js var x = JSON.stringify({"underscore_thing": "other_thing"}); var y= JSON.parse(x); y

Returned: aggregate string [string]
underscore_thing => other_thing
```
went fine, so I think this is okay other than the round-trip breaking for proxies.

**Comment by gausie** [comment]
Yeah you're right this is wrong - it's returning a stringified... string. Annoying. I will close this and re-open when I've got it ifxed.

**Comment by gausie** [comment]
Oh I worked out how to actually do this and it is right now

**Review by midgleyc — APPROVED** [review]
Looks good, can't break it.

Objects with underscore keys work (i.e. are not transformed).
Items with quotes work.
Parsing works.
Only JavaScript is affected, no ASH leaks (that I found).

**Pull request merged**
