### PR TITLE
tests: speed up maximizer tests

### PR DESCRIPTION
**Pull request by midgleyc**
`KoLCharacter.reset(true)` is pretty slow (in part due to `KoLCharacter.currentModifiers.resetModifiers()`, which parses the entire `modifiers.txt` file again).

For maximizer tests (the ones I work on the most), do a more targeted teardown, focusing on restoring exactly what was set up to the baseline.

Also split out the regression tests to a different file.

### CODE REVIEW

**Comment by gausie** [comment]
Commenting here with my suggestion I made via DM to make the cleanup concept (which is good) instead be something around `try with resources`

**Review by jaadams5 — APPROVED** [review]
I'm OK with this.  I'm not sure about try with resources but I have no problem with doing so.

**Comment by gausie** [comment]
Sorry to add a little bit of conflict res to Player.java, it should hardly be anything

**Comment by midgleyc** [comment]
Rebased.

try-with-resources isn't as good as hoped, because I have to create a variable to store the cleanup in -- I can't just leave it anonymous.

Also `spotless` insists on putting each variable in the block on its own line, which I'm really not keen on.

I could move the variable declarations inside the block. I initially thought it was cleaner outside but I'm not sure.

**Review by jaadams5 — APPROVED** [review]

**Pull request merged**
