### PR TITLE
Primary lab

### PR DESCRIPTION
**Pull request by Veracity0**
Add tiny plastic primary lab. It has no visible Enchantments. If they fix that, we'll have to update.
Add support for Choice Adventure 1461 in the Site Alpha Primary Lab.
Note that option #5 is "Grab the Cheer Core". If I recall, you get that once - and it is your only choice.
Therefore, if you are automating and that choice comes up and that option is present, we select it, regardless of how you have the choice configured.
Note also that this choice adventure does not have a blue "Encounter" when you find it.
I bug reported it to KoL. Surely they'd prefer to have something funny, rather than nothing.

Also added two properties:

primaryLabGooIntensity (default 10)
primaryLabCheerCoreGrabbed (default false)

### CODE REVIEW

**Comment by gausie** [comment]
Thanks V. We could use deriving the current intensity from the construct names too.

**Comment by Veracity0** [comment]
> Thanks V. We could use deriving the current intensity from the construct names too.

Well, if it says 10-ton, that means intensity is no greater than 10, but it could be less.
Do I need to do this before you'll approve? :)

**Comment by Veracity0** [comment]
Also added the name change: inert grey goo ring -> ert grey goo ring.
Without this, cannot do mall search for it.

**Comment by gausie** [comment]
> > Thanks V. We could use deriving the current intensity from the construct names too.
> 
> Well, if it says 10-ton, that means intensity is no greater than 10, but it could be less. Do I need to do this before you'll approve? :)

Of course not!

**Review by gausie — APPROVED** [review]

**Pull request merged**
