### PR TITLE
feat: add is_shruggable/is_removable script functions

### PR DESCRIPTION
**Pull request by oxc**
Add two RuntimeLibrary functions for checking whether an effect is shruggable or removable (UneffectRequest.isShruggable/isRemovable).

### CODE REVIEW

**Review by jaadams5 — APPROVED** [review]
The code is fine.  I would like someone else's opinion as to whether these functions are needed/useful/cannot be easily scripted.  I would also love to see some tests.  But if anyone thinks otherwise and wants to push this then I'm fine with that decision.

**Comment by oxc** [comment]
The main reason I added isShruggable so I can safely "cli uneffect" an effect without risking kolmafia buying SGEEAs (if I haven't misunderstood something there...)

**Comment by midgleyc** [comment]
If you've got a use for them, I think that's good enough.

I've definitely added functions that I think I'm the only person to use.

**Comment by oxc** [comment]
This might be slightly related: https://github.com/loathers/libram/issues/512

It's all not a satisfying solution for the underlying problem, but better than nothing.

**Comment by jaadams5** [comment]
OK.  Pushing.

**Pull request merged**
