### PR TITLE
Language Server - interruptions

### PR DESCRIPTION
**Pull request by fredg1**
The language server will run the parsing of the various scripts in separate threads.

This allows us to save resources by allowing those threads to be interrupted when we no longer need them (if, for example, a file is modified during parsing).

Is this a behaviour that needs to be tested? Not sure how I'd even test that.

### CODE REVIEW

**Comment by gausie** [comment]
Fred the answer is always yes. Definition of insanity and all that...

**Comment by fredg1** [comment]
but *how*

I can't just start the parsing in a new thread and "hope" I interrupt the parsing before it's over.

**Comment by gausie** [comment]
By mocking importFile to throw the exception

**Comment by fredg1** [comment]
> By mocking importFile to throw the exception

which? one is not called during parsing, and the other is private.

**Comment by fredg1** [comment]
(can you mock a method even if it's private? I forgot)

**Review by gausie — APPROVED** [review]
Not the test I expected but that'll do I guess

**Pull request merged**
