### PR TITLE
feat: cookbookbat cooks

### PR DESCRIPTION
**Pull request by midgleyc**
Cookbookbat offers 5 free cooks per day.

Not too sure as to whether the ConcoctionDatabase changes are right: I don't understand what `adventureSmithingLimit` and the like do, and whether we need a corresponding one for cooking. Also everything that refers to Jewelrycrafting taking adventures can presumably be removed?

### CODE REVIEW

**Comment by gausie** [comment]
This probably wants tests for crafting order

**Comment by midgleyc** [comment]
I think this probably wants tests all over the place ;). It's just a lot of work to set up for the first time.

Plus ConcoctionDatabase wants a bit of cleanup after tests are in place.

**Review by gausie — APPROVED** [review]

**Comment by midgleyc** [comment]
Not having any luck making these tests. In `ConcoctionTest`:

```java
@Test
public void smithingTakesAdventures() {
  var cleanups = new Cleanups(withItem(ItemPool.TENDER_HAMMER), withMeat(1000), withAdventuresLeft(5));

  ConcoctionDatabase.refreshConcoctions();

  var con = ConcoctionPool.get(ItemPool.MACE_OF_THE_TORTOISE);
  assertThat(con.getAdventuresNeeded(1), is(1));
}
```
This fails, and debugging says the character can't smith. I don't understand how or why.

**Comment by Veracity0** [comment]
> Not having any luck making these tests. In `ConcoctionTest`:
> 
> ```
> var con = ConcoctionPool.get(ItemPool.MACE_OF_THE_TORTOISE);
> ```
> 
> This fails, and debugging says the character can't smith. I don't understand how or why.

Mace of the Tortoise is not creatable; it is given to you by the ghost of The Unknown Turtle Tamer.

**Pull request merged**
