### PR TITLE
Remove accountval from scripts

### PR DESCRIPTION
**Pull request by libraryaddict**

### CODE REVIEW

**Comment by jaadams5** [comment]
What is the trigger for doing this?  Did the author ask or is no one maintaining it anymore or what?

**Comment by libraryaddict** [comment]
I am the author.
Lost passion for the game and the script was too much of a personal project for me.

**Review by midgleyc — APPROVED** [review]
Sorry to see you go, but thanks for the cleanup!

**Comment by jaadams5** [comment]
> I am the author. Lost passion for the game and the script was too much of a personal project for me.

Thank you.  Author's request is a pretty good reason to remove something.

**Pull request merged**
